# Generated by Django 3.2.9 on 2022-01-18 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_auto_20220118_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuserprofile',
            name='vk_page',
            field=models.CharField(blank=True, max_length=30, verbose_name='ID страницы в VK'),
        ),
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 15, 59, 32, 401899, tzinfo=utc)),
        ),
    ]
